
CREATE TABLE IF NOT EXISTS "CompanyType" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"description"	TEXT 
);

CREATE TABLE IF NOT EXISTS "Company" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"idCompanyType"	INTEGER NOT NULL,
	"logo"	TEXT 
);

CREATE TABLE IF NOT EXISTS "MeterType" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"description"	TEXT,
	"logo"	TEXT
);

CREATE TABLE IF NOT EXISTS "Meter" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"serialNumber"	TEXT NOT NULL,
	"meterTypeId"	INTEGER NOT NULL,
	"companyId"	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "MeterReading" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"meterId"	INTEGER NOT NULL,
	"reading"	REAL NOT NULL,
	"createdAt"	TEXT NOT NULL,
	"updatedAt"	TEXT NOT NULL
);